services:
  db:
    image: mysql/mysql-server:8.0
    container_name: go-todo-mysql
    restart: always
    ports:
      - "33060:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=go_todo_local
      - MYSQL_ROOT_HOST=%
    volumes:
      - go-todo-mysql-data:/var/lib/mysql
      - ./docker/local/mysql/config/my.cnf:/etc/mysql/my.cnf
    networks:
      - go-todo-network

  app:
    image: go-todo-backend-image
    container_name: go-todo-backend
    depends_on:
      - db
    # DBコンテナが起動するまで待たないとエラーになる
    entrypoint: ["sh", "-c", "./wait-for.sh db:3306 -- ./local_entrypoint.sh"]
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./:/go/src/app
    ports:
      - "8090:8090"
    networks:
      - go-todo-network

volumes:
  go-todo-mysql-data:

networks:
  go-todo-network:
