services:
  db:
    image: mysql/mysql-server:8.0
    container_name: go-todo-mysql
    restart: always
    ports:
      - "33060:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=go_todo_local
      - MYSQL_ROOT_HOST=%
    volumes:
      - go-todo-mysql-data:/var/lib/mysql
      - ./docker/local/mysql/config/my.cnf:/etc/mysql/my.cnf
volumes:
  go-todo-mysql-data:
